sudo: required
services:
  - docker

before_install:
  - docker build -t yailsan/docker-tut -f Dockerfile.dev .

script:
  - docker run yailsan/docker-tut npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-tut"
  env: "DockerTut-env"
  bucket_name: "elasticbeanstalk-us-west-2-371627042657"
  bucket_path: "docker-tut"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"